name: multi-line-commands on files and some more commands

on: workflow_dispatch

jobs:
    command:
        runs-on: ubuntu-latest
        steps:
            - name: checkout the repository
              uses: actions/checkout@v6
            
            - name: display the content of a file and some more commands.
              run: | 
               cat devops.txt
               chmod +x uptime.sh
               ./uptime.sh
               ls -lrtha
            - name: running java and python
              run: |
               MathExample.java
               fibonacci series.py
