name: executing shell scripting programme

on: workflow_dispatch

jobs:
    files:
        runs-on: ubuntu-latest
        steps:
            - name: checkout the repository
              uses: actions/checkout@v6
            
            - name: display the content of a file
              run: cat devops.txt

            - name: display the date
              run: date

            - name: display files and directories
              run: ls -lrth
            
            - name: display th present location
              run: pwd

            - name: execute the shell scripting
              run: ./uptime.sh
